### ISSUE TITLE
ServerListPingEvent, nie mam pojęcia jak coś.

### ISSUE THREAD

**Issue by Freaksy** [Thefilippop1PL/Anti-Bot#1]
Czy przypadkiem w tym evencie nie można pobrać adresu który pinguje? Nie wydaje Mi się, żeby boty pingowały skoro są consolowe, i wysyłają wejście na serwer. Nie mam pojęcia czy to bedzie śmigać, i nie mam czasu żeby na to luknąć, ale gdyby tak sprawdzać czy adress pingował, hashmapa, z adresem i boolean, i potem sprawdzać że jeśli nie pingował to bot ?

**Comment by TheMolkaPL** [comment]
Masz rację, boty nie pingują, ale to nie znaczy, że ludzie muszą. Wystarczy, że połączy się poprzez Direct Connect. ServerListPingEvent [ma możliwość pobrania adresu IP](http://jd.bukkit.org/rb/apidocs/org/bukkit/event/server/ServerListPingEvent.html#getAddress()) gracza. Jednak można wprowadzić opcję blokowania wchodzenia graczy, którzy nie pingowali wcześniej serwera na przykład w ciągu 10 - 15 sekund.

**Comment by Freaksy** [comment]
Direct connect, jest możliwy do kliknięcia po wejściu na liste serwerów, co wywołuje efekt pingowania. Nie możliwe bo podczas korzystania z normalnej wersji mc przez gracza, nie wywołano pingu przy wejsciu na serwer.

**Comment by TheMolkaPL** [comment]
Dodano w wersji 1.1.
